### ISSUE TITLE
Does psn provide an official api to send messages to friends?

### ISSUE THREAD

**Issue by huazaizhang** [achievements-app/psn-api#133]
Does psn provide an official api to send messages to friends?

**Comment by huazaizhang** [comment]
I found on github that the psnjs and psn-api-python projects mentioned using the following api:
`
MESSAGE_THREADS_URL = 'https://es-gmsg.np.community.playstation.net/groupMessaging/v1/threads'
MESSAGE_USERS_URL = 'https://es-gmsg.np.community.playstation.net/groupMessaging/v1/users/'
SEND_MESSAGE_URL = 'https://es-gmsg.np.community.playstation.net/groupMessaging/v1/messageGroups/'
`
I try to use my own account accessToken to access:
https://hk-gmsg.np.community.playstation.net/groupMessaging/v1/users/tangy_crayon1/messageGroups
but returns:
`
{
     "error": {
         "code": 2122246,
         "message": "Not authorized"
     }
}
`

**Comment by huazaizhang** [comment]
@wescopeland  @travisrroy @Azimiao @isFakeAccount 
Have any of you encountered this problem and can give me some help?

**Comment by TheYuriG** [comment]
I suspect this API endpoint was disabled when Sony had a big influx of message spammers inviting users to join a telegram group to buy stolen PS4 accounts with games for a portion of the price. Or maybe it wasn't and it was moved to the `.com` domain since the `.net` domain was killed last year. Have you tried requesting to `.com` instead?

There must still be a way to do it since that feature is available on the PS App for phones, but I don't think any of us found the endpoint to do it yet. As it is, is possible to do it and we just don't know how _yet_. #119 is about this very same thing, I believe.

If anyone else knows more, feel free to chime in (and possibly correct me).

**Comment by huazaizhang** [comment]
@TheYuriG

**Comment by huazaizhang** [comment]
@TheYuriG Anyway thank you very much.

**Comment by isFakeAccount** [comment]
Like @TheYuriG mentioned, nothing here is official. All the endpoints are reversed engineered from PlayStation app. I don't think there ever will be an offical api, even if there is, it will be hidden behind a paywall or a developer program.

Now with that out the way, yes there are endpoints for sending messages to other users, I added them to my API wrapper https://github.com/isFakeAccount/psnawp quite a while ago. It supports text messages only for now.

If you are ok with python then you can use my api wrapper. Just try not to spam, otherwise Sony will find out and change the endpoint.

**Comment by wescopeland** [comment]
Closing in favor of https://github.com/achievements-app/psn-api/issues/119.

Ideally, we should be able to reference @isFakeAccount's Python library to better understand how to fit this into psn-api.
