### ISSUE TITLE
Migration impossible with my account psn i didn't know why

### ISSUE THREAD

**Issue by Lagueule** [achievements-app/psn-api#142]

**Comment by wescopeland** [comment]
Hi @Lagueule,

In order to assist you more effectively, I need additional information regarding the problem you're encountering. Could you please provide more details like:

* The specific step at which you encounter this problem
* Error messages (if any)
* The expected and actual behavior
* 
Without this information, I'm unable to investigate your issue. Therefore, I'm going to close this issue for now. Please feel free to reopen it when you're able to provide the details requested above.

Thanks for your understanding.

**Comment by wescopeland** [comment]
What is the error message and what code are you using?

**Comment by wescopeland** [comment]
For me to further assist you, I need the error message and the code you are using.

**Comment by wescopeland** [comment]
Hi,

This library has no official relationship with Sony or PlayStation. Unfortunately, I'm not sure how to help you with your situation, as it sounds unrelated to psn-api. I recommend contacting the app authors or PlayStation Support to help resolve the issues you're currently facing.

Thanks!
